name: Run Unit Tests
description: Runs unit tests for a specific version of Python
inputs:
  python-version:
    description: The version of Python to test against
    required: true
runs:
  using: 'composite'
  steps:
    - name: Check if relevant files changed
      if: github.event_name == 'pull_request_target'
      # https://github.com/marketplace/actions/paths-changes-filter
      # For each filter, it sets output variable named by the filter to the text:
      #  'true' - if any of changed files matches any of filter rules
      #  'false' - if none of changed files matches any of filter rules
      # also, returns:
      #  `changes` - JSON array with names of all filters matching any of the changed files
      uses: dorny/paths-filter@v2
      id: get-changes
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        filters: |
          snowflake:
            - 'dbt/**'
            - 'tests/**'
            - 'pyproject.toml'

    - name: Generate integration test matrix
      id: generate-matrix
      uses: actions/github-script@v6
      env:
        CHANGES: ${{ steps.get-changes.outputs.changes }}
      with:
        script: |
          const script = require('./.github/scripts/integration-test-matrix.js')
          const matrix = script({ context })
          console.log(matrix)
          return matrix
