select
    1::smallint as smallint_col,
    2::int as int_col,
    3::bigint as bigint_col,
    4::int2 as int2_col,
    5::int4 as int4_col,
    6::int8 as int8_col,
    7::integer as integer_col,
    8.0::real as real_col,
    9.0::float4 as float4_col,
    10.0::float8 as float8_col,
    11.0::float as float_col,
    12.0::double precision as double_col,
    13.0::numeric as numeric_col,
    14.0::decimal as decimal_col,
    '15'::varchar(20) as varchar_col,
    '16'::text as text_col
