[version]
path = "dbt/adapters/snowflake/__version__.py"

[build.targets.sdist]
packages = ["dbt"]

[build.targets.wheel]
packages = ["dbt"]

[envs.default]
dependencies = [
    "dbt-adapters @ git+https://github.com/dbt-labs/dbt-adapters.git",
    "dbt-common @ git+https://github.com/dbt-labs/dbt-common.git",
    "dbt-tests-adapter @ git+https://github.com/dbt-labs/dbt-adapters.git#subdirectory=dbt-tests-adapter",
    "dbt-core @ git+https://github.com/dbt-labs/dbt-core.git#subdirectory=core",
    "ddtrace==2.3.0",
    "ipdb~=0.13.13",
    "pre-commit~=3.7.0",
    "pytest~=7.4",
    "pytest-csv~=3.0",
    "pytest-dotenv~=0.5.2",
    "pytest-logbook~=1.2",
    "pytest-xdist~=3.6",
]

[envs.default.scripts]
setup = "pre-commit install"
code-quality = "pre-commit run --all-files"
unit-tests = "python -m pytest {args:tests/unit}"
integration-tests = [
    "- python -m pytest tests/functional/adapter/catalog_tests {args}",
    "- python -m pytest tests/functional/adapter/column_types {args}",
    "- python -m pytest tests/functional/adapter/custom_schema_tests {args}",
    "- python -m pytest tests/functional/adapter/dbt_clone {args}",
    "- python -m pytest tests/functional/adapter/dbt_show {args}",
    "- python -m pytest tests/functional/adapter/empty {args}",
    "- python -m pytest tests/functional/adapter/incremental {args}",
    "- python -m pytest tests/functional/adapter/list_relations_tests {args}",
    "- python -m pytest tests/functional/adapter/python_model_tests {args}",
    "- python -m pytest tests/functional/adapter/query_comment_tests {args}",
    "- python -m pytest tests/functional/adapter/simple_copy {args}",
    "- python -m pytest tests/functional/adapter/simple_seed {args}",
    "- python -m pytest tests/functional/adapter/statement_test {args}",
    "- python -m pytest tests/functional/adapter/unit_testing {args}",
    "- python -m pytest tests/functional/adapter/utils {args}",
    "- python -m pytest tests/functional/adapter/test_aliases.py {args}",
    "- python -m pytest tests/functional/adapter/test_anonymous_usage_stats.py {args}",
    "- python -m pytest tests/functional/adapter/test_basic.py {args}",
    "- python -m pytest tests/functional/adapter/test_caching.py {args}",
    "- python -m pytest tests/functional/adapter/test_changing_relation_type.py {args}",
    "- python -m pytest tests/functional/adapter/test_concurrency.py {args}",
    "- python -m pytest tests/functional/adapter/test_constraints.py {args}",
    "- python -m pytest tests/functional/adapter/test_emphemeral.py {args}",
    "- python -m pytest tests/functional/adapter/test_get_last_relation_modified.py {args}",
    "- python -m pytest tests/functional/adapter/test_grants.py {args}",
    "- python -m pytest tests/functional/adapter/test_incremental_microbatch.py {args}",
    "- python -m pytest tests/functional/adapter/test_persist_docs.py {args}",
    "- python -m pytest tests/functional/adapter/test_python_model.py {args}",
    "- python -m pytest tests/functional/adapter/test_simple_snapshot.py {args}",
    "- python -m pytest tests/functional/adapter/test_timestamps.py {args}",
]
docker-dev = [
    "docker build -f docker/dev.Dockerfile -t dbt-snowflake-dev .",
	"docker run --rm -it --name dbt-snowflake-dev -v $(pwd):/opt/code dbt-snowflake-dev",
]

[envs.build]
detached = true
dependencies = [
    "wheel",
    "twine",
    "check-wheel-contents",
]

[envs.build.scripts]
check-all = [
    "- check-wheel",
    "- check-sdist",
]
check-wheel = [
    "twine check dist/*",
    "find ./dist/dbt_snowflake-*.whl -maxdepth 1 -type f | xargs python -m pip install --force-reinstall --find-links=dist/",
    "pip freeze | grep dbt-snowflake",
]
check-sdist = [
    "check-wheel-contents dist/*.whl --ignore W007,W008",
    "find ./dist/dbt_snowflake-*.gz -maxdepth 1 -type f | xargs python -m pip install --force-reinstall --find-links=dist/",
    "pip freeze | grep dbt-snowflake",
]
docker-prod = "docker build -f docker/Dockerfile -t dbt-snowflake ."
