name: Archive Test Results
description: Archives the test results output from pytest
inputs:
  python-version:
    description: The version of python to be used in the file name
    required: true
  file-name-stub:  # e.g. unit, integration
    description: The file name stub to be used at the beginning of the file name
    required: true
runs:
  using: 'composite'
  steps:
    - id: get-date
      shell: bash
      run: echo "result=$(date +'%Y-%m-%dT%H_%M_%S')" >> $GITHUB_OUTPUT  # no colons allowed for artifacts
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.file-name-stub }}_${{ inputs.python-version }}_${{ steps.get-date.outputs.result }}.csv
        path: test_results.csv
