name: Archive Unit Tests / Python ${{ inputs.python-version }}
inputs:
  python-version:
    required: true
  file-name-stub:  # e.g. unit, integration
    required: true
runs:
  using: 'composite'
  steps:
    - name: Get current date
      if: always()
      id: date
      run: echo "date=$(date +'%Y-%m-%dT%H_%M_%S')" >> $GITHUB_OUTPUT  # no colons allowed for artifacts
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ${{ inputs.file-name-stub }}_${{ inputs.python-version }}-${{ steps.date.outputs.date }}.csv
        path: test_results.csv
