name: Run Integration Tests
description: Runs integration tests for a specific version of Python
inputs:
  python-version:
    description: The version of Python to test against
    required: true
  dbt-core-branch:
    description: The branch of dbt-core to test against
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --user --upgrade pip
        python -m pip install .[test]
    - name: Update pyproject.toml
      if: inputs.dbt-core-branch != ''
      shell: bash
      run: |
        python -m pip install bumpversion
        ./.github/scripts/update_dbt_core_branch.sh ${{ inputs.dbt-core-branch }}
        python -m pip install --force-reinstall .
    - name: Run integration tests
      env:
        DBT_INVOCATION_ENV: github-actions
        DD_CIVISIBILITY_AGENTLESS_ENABLED: true
        DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        DD_SITE: datadoghq.com
        DD_ENV: ci
        DD_SERVICE: ${{ github.event.repository.name }}
      shell: bash
      run: python -m pytest tests/functional --ddtrace
