name: Run Unit Tests
description: Runs unit tests for a specific version of Python
inputs:
  python-version:
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --user --upgrade pip
        python -m pip install .[test]
    - name: Run unit tests
      shell: bash
      run: python -m pytest tests/unit
