name: Run Unit Tests
inputs:
  python-version:
    required: true
    default: '3.8'
defaults:
  run:
    shell: bash
runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --user --upgrade pip
        python -m pip install .[test]
    - name: Run unit tests
      run: python -m pytest tests/unit
