name: Run Code Quality
description: Runs all pre-commit checks, including linters, formatters, mypy, etc.
runs:
  using: 'composite'
  steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --user --upgrade pip
        python -m pip install .[dev]
    - name: Run pre-commit hooks
      shell: bash
      run: pre-commit run --all-files --show-diff-on-failure
