# **what?**
# Add a changelog (changie) to a Dependency or Security PR with the appropriate template:
#
#     kind: <per action matrix>
#     body: <PR title>
#     time: <current timestamp>
#     custom:
#       Author: <PR User Login (generally the bot)>
#       PR: <PR number>
#
# **why?**
# Standardize and automate the changelog generation for boilerplate PRs.
#
# **how?**
# Add a relevant label (one in the include matrix) to an open PR.
#
# **when?**
# If the PR is created with a relevant label, when the PR is created.
# After the PR is created and before the PR is merged, when a relevant label is applied to the PR.

name: Bot Changelog
on:
  pull_request:
    types: [opened, labeled]
permissions:
  contents: write
  pull-requests: read
jobs:
  bot-changelog:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - label: "dependencies"
            changie-kind: "Dependencies"
          - label: "snyk"
            changie-kind: "Security"
    steps:
    - name: Create and commit changelog on bot PR
      if: contains(github.event.pull_request.labels.*.name, ${{ matrix.label }})
      uses: emmyoop/changie_bot@v1
      with:
        GITHUB_TOKEN: ${{ secrets.FISHTOWN_BOT_PAT }}
        commit_author_name: "Github Build Bot"
        commit_author_email: "<buildbot@fishtownanalytics.com>"
        commit_message: "Add automated changelog yaml from template for bot PR"
        changie_kind: ${{ matrix.changie-kind }}
        label: ${{ matrix.label }}
        custom_changelog_string: "custom:\n  Author: ${{ github.event.pull_request.user.login }}\n  PR: ${{ github.event.pull_request.number }}"
