# **what?**
# Creates a new branch named `1.<minor>.latest`.
# Cleans up files in `.changes/unreleased` and `.changes/<previous version>` on `main`.
# Bumps `main` to the input version.
#
# **why?**
# Standardize and automate boilerplate processes.
#
# **how?**
# Run the workflow and provide inputs.
#
# **when?**
# Manually triggered.

name: Cut new release branch
on:
  workflow_dispatch:
    inputs:
      new-main-version:
        description: 'The alpha version main should bump to (e.g. 1.6.0a1)'
        required: true
      new-release-branch:
        description: 'The full name of the new branch (e.g. 1.5.latest)'
        required: true
defaults:
  run:
    shell: bash
permissions:
  contents: write
jobs:
  cut-branch:
    uses: dbt-labs/actions/.github/workflows/cut-release-branch.yml@main
    with:
      version_to_bump_main: ${{ inputs.new-main-version }}
      new_branch_name: ${{ inputs.new-release-branch }}
      PR_title: "Cleanup main after cutting new ${{ inputs.new_branch_name }} branch"
      PR_body: "This PR will fail CI until the dbt-core PR has been merged due to release version conflicts."
    secrets:
      FISHTOWN_BOT_PAT: ${{ secrets.FISHTOWN_BOT_PAT }}
