# **what?**
# Open an issue in docs.getdbt.com and link it to this PR.
#
# **why?**
# Encourage keeping user docs up to date.
#
# **when?**
# Apply the label `user docs` to a PR.
#
# **when?**
# When the PR is merged.

name: Open issues in docs.getdbt.com repo when a PR is labeled
on:
  pull_request_target:
    types: [labeled, closed]
defaults:
  run:
    shell: bash
permissions:
    issues: write # opens new issues
    pull-requests: write # comments on PRs
jobs:
  open-issues:
    if: |
      (github.event.pull_request.merged == true) &&
      (
        (github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, 'user docs')) ||
        (github.event.action == 'labeled' && github.event.label.name == 'user docs')
      )
    uses: dbt-labs/actions/.github/workflows/open-issue-in-repo.yml@main
    with:
        issue_repository: "dbt-labs/docs.getdbt.com"
        issue_title: "Docs Changes Needed from ${{ github.event.repository.name }} PR #${{ github.event.pull_request.number }}"
        issue_body: "At a minimum, update body to include a link to the page on docs.getdbt.com requiring updates and what part(s) of the page you would like to see updated."
    secrets: inherit
