# **what?**
# Mirrors GitHub labels into Jira.
#
# **why?**
# Jira is our tool for issue tracking and upstream reporting but users submit issues via GitHub.
#
# **how?**
# Add/remove a label to/from a GitHub issue.
#
# **when?**
# The label is added/removed to/from the GitHub issue.

name: Jira Label Mirroring
on:
  issues:
    types: [labeled, unlabeled]
permissions:
  issues: read
jobs:
  call-label-action:
    uses: dbt-labs/actions/.github/workflows/jira-label.yml@main
    with:
      project_key: ADAP
    secrets:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
