# **what?**
# Mirrors issues into Jira, including the title, GitHub Issue ID, and URL.
# Updates GitHub issue to include the Jira issue key in the title.
#
# **why?**
# Jira is our tool for issue tracking and upstream reporting but users submit issues via GitHub.
#
# **how?**
# Create a GitHub issue.
# Label a GitHub issue with the `Jira` label.
#
# **when?**
# A GitHub issue is created or labelled.

name: Jira Issue Creation
on:
  issues:
    types: [opened, labeled]
permissions:
  issues: write
jobs:
  create-jira-issue:
    uses: dbt-labs/actions/.github/workflows/jira-creation.yml@main
    with:
      project_key: ADAP
    secrets:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
