# **what?**
# Mirror the GitHub issue status into Jira.
#
# **why?**
# Jira is our tool for issue tracking and upstream reporting but users submit issues via GitHub.
#
# **how?**
# Close, delete, or reopen a GitHub issue.
#
# **when?**
# The GitHub issue is closed, deleted, or reopened.

name: Jira Issue Transition
on:
  issues:
    types: [closed, deleted, reopened]
permissions: read-all
jobs:
  call-label-action:
    uses: dbt-labs/actions/.github/workflows/jira-transition.yml@main
    with:
      project_key: ADAP
    secrets:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
