# **what?**
# Scheduled CI runs tests on `main`.
# If the CI workflow fails for a branch, it will post to dev-adapter-alerts to raise awareness.
#
# **why?**
# Ensure `main` is always shippable.
# Catch regressions due to dependencies shifting beneath us.
#
# **how?**
# Scheduled. Triggers other workflows (main.yml and integration.yml).
# Manually run via GitHub Actions.
#
# **when?**
# Scheduled daily at 9:00, 13:00, 18:00 UTC.
# Manually triggered.

name: Main branch scheduled testing
on:
  schedule:
    - cron: '0 9,13,18 * * *' # 9:00, 13:00, 18:00 UTC
  workflow_dispatch:
permissions: read-all
jobs:
  kick-off-ci:
    name: Kick-off CI
    runs-on: ubuntu-latest
    strategy:
      # must run CI 1 branch at a time b/c the workflow-dispatch Action polls for
      # latest run for results and it gets confused when we kick off multiple runs
      # at once. There is a race condition so we will just run in sequential order.
      max-parallel: 1
      fail-fast: false
      matrix:
        branch: [main]
        workflow: [main.yml, integration.yml]
    steps:
    - id: run-workflow
      uses: aurelien-baudet/workflow-dispatch@v2
      with:
        workflow: ${{ matrix.workflow }}
        ref: ${{ matrix.branch }}
        token: ${{ secrets.FISHTOWN_BOT_PAT }}
    - uses: ravsamhq/notify-slack-action@v2
      if: ${{ always() && !contains(steps.run-workflow.outputs.workflow-conclusion,'success') }}
      with:
        status: ${{ job.status }}
        notification_title: 'dbt-snowflake scheduled run of ${{ matrix.workflow }} on "${{ matrix.branch }}" branch not successful'
        message_format: ':x: ${{ matrix.workflow }} CI on branch "${{ matrix.branch }}" ${{ steps.run-workflow.outputs.workflow-conclusion }}'
        footer: 'Linked failed CI run ${{ steps.run-workflow.outputs.workflow-url }}'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEV_ADAPTER_ALERTS }}
