# **what?**
# Deletes branches and draft releases left over from automation, testing, and release testing.
#
# **why?**
# Scheduled workflows leave behind branches and draft releases that clutter the repository.
# Sometimes we need them to debug processes so we don't want them immediately deleted.
#
# **when?**
# Scheduled weekly at 12:00 UTC on Saturday.
#     Runs on Saturday to avoid interrupting actual releases.
# Manually triggered.

name: Repository Cleanup
on:
  schedule:
    - cron: '0 12 * * SAT' # 12:00 UTC on Saturday
  workflow_dispatch:
permissions:
  contents: write
jobs:
  cleanup-repo:
    uses: dbt-labs/actions/.github/workflows/repository-cleanup.yml@main
    secrets: inherit
